version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: audicon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cqc_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: audicon_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env.example
    environment:
      DB_HOST: db
      NODE_ENV: development
    command: ["node", "dist/main.js"]

volumes:
  postgres_data: