import { Unit } from '../../units/entities/unit.entity';
import { InfractionImage } from './infraction-image.entity';
import { InfractionSeverity } from '../enums/infraction-severity.enum';
import {
  Column,
  CreateDateColumn,
  DeleteDateColumn,
  Entity,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
export enum InfractionStatus {
  PENDING = 'pending',
  ANALYZED = 'analyzed',
  APPROVED = 'approved',
  SENT = 'sent',
}
@Entity()
export class Infraction {
  @PrimaryGeneratedColumn()
  id: number;
  @Column({ type: 'text', comment: 'Informal description provided by staff.' })
  description: string;
  @Column({
    type: 'enum',
    enum: InfractionSeverity,
    comment: 'Severity classified by the operator at registration (required).',
  })
  severity: InfractionSeverity;
  @Column({
    type: 'text',
    nullable: true,
    comment: 'Formal description generated by AI.',
  })
  formalDescription: string;
  @Column({
    nullable: true,
    comment: 'Suggested penalty by AI (e.g., Notice, Warning, Fine).',
  })
  suggestedPenalty: string;
  @Column({
    type: 'enum',
    enum: InfractionStatus,
    default: InfractionStatus.PENDING,
    comment: 'Current state of the infraction in the workflow.',
  })
  status: InfractionStatus;
  @CreateDateColumn()
  occurrenceDate: Date;
  @UpdateDateColumn()
  updatedAt: Date;
  @Column({
    type: 'timestamp',
    nullable: true,
    comment: 'When the infraction was approved by staff.',
  })
  approvedAt: Date | null;
  @Column({
    type: 'timestamp',
    nullable: true,
    comment: 'When the infraction notification was sent to the resident.',
  })
  sentAt: Date | null;
  @Column({
    type: 'timestamp',
    nullable: true,
    comment: 'When the WhatsApp alert was sent to the resident.',
  })
  whatsappSentAt: Date | null;
  @ManyToOne(() => Unit, (unit) => unit.infractions)
  unit: Unit;
  @OneToMany(() => InfractionImage, (image) => image.infraction)
  images: InfractionImage[];
  @DeleteDateColumn({ type: 'timestamp', nullable: true })
  deletedAt: Date | null;
}
